---
# tasks file for ec2-bootstrap

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"

- name: Install initial packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ osbootstrap_packages }}"
  when: osbootstrap_packages is defined

- name: Set timezone
  file:
    src: "/usr/share/zoneinfo/{{ osbootstrap_timezone }}"
    dest: /etc/localtime
    force: yes
    state: link
  when: osbootstrap_timezone is defined

- name: Display OS info before update
  debug:
    msg:
      - "OS: {{ ansible_distribution }}"
      - "Release: {{ ansible_distribution_version }}"
      - "Architecture: {{ ansible_architecture }}"
      - "Platform: {{ ansible_product_name }}"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
