---
# Run these tasks if we call for a reboot

- name: EL5/EL6 | Reboot host if we call for a reboot
  shell: sleep 5 ; /sbin/shutdown -r ; echo &
  when:
    - rebootrequired
    - ansible_distribution_major_version | version_compare('6', '<=')

- name: EL7 | Reboot host if we call for a reboot
  command: /usr/bin/systemd-run --on-active=10 /usr/bin/systemctl reboot
  async: 0
  poll: 0
  when:
    - rebootrequired
    - ansible_distribution_major_version | version_compare('7', '=')

- name: Wait for host sshd if we call for a reboot
  local_action:
    module: wait_for
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    port: 22
    timeout: 50
    delay: 20
  become: no
  when:
    - rebootrequired

- name: Display conditionals for this request
  debug:
    msg: "rebootrequired is {{ rebootrequired }} and ansible_os_family is {{ ansible_os_family }} and ansible_distribution_major_version is {{ ansible_distribution_major_version }}"

