---
# tasks file for ec2-setup | RHEL

- name: Include distro-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    -  default.yml

- name: Install epel
  yum:
    name: "{{ ec2_setup_epel_pkg }}"
    state: present
  when: ec2_setup_epel

- name: Install various packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ ec2_setup_packages }}"

- name: Configure SELinux
  selinux:
    policy: "{{ item.policy }}"
    state: "{{ item.state }}"
  with_items: "{{ ec2_setup_selinux }}"

- name: Set timezone
  file:
    src: "/usr/share/zoneinfo/{{ ec2_setup_timezone }}"
    dest: /etc/localtime
    force: yes
    state: link

- name: Update system
  yum:
    name: "*"
    state: latest
  when: rebootrequired

- include: reboot.yml
  when: rebootrequired
