---
# tasks file for ec2-setup | RHEL

- name: Install python selinux libraries
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ ec2_setup_python_redhat }}"

- name: Set timezone
  file:
    src: "/usr/share/zoneinfo/{{ ec2_setup_timezone }}"
    dest: /etc/localtime
    force: yes
    state: link
