---
# tasks file for ec2-bootstrap | RHEL

- name: EL | Enable EPEL repository
  yum:
    name: "{{ osbootstrap_epel_repo }}"
    state: present
  when: osbootstrap_epel

- name: EL | Install various packages from EPEL
  yum:
    name: "{{ item }}"
    state: present
    enablerepo: epel
  with_items: "{{ osbootstrap_epel_packages }}"
  when: osbootstrap_epel

- name: EL | Configure SELinux.
  selinux:
    policy: "{{ item.policy }}"
    state: "{{ item.state }}"
  with_items: "{{ osbootstrap_selinux }}"

- name: EL | Run system update
  yum:
    name: "*"
    state: latest
    update_cache: true
  when: reboot
  register: yum_result

- debug:
    var: yum_result

- name: EL7 | Check if reboot is required
  command: needs-restarting -r
  register: needs_restarting
  changed_when: false
  failed_when: needs_restarting.rc == 2
  when:
    - reboot
    - ansible_distribution_major_version | version_compare('7', "=")

- name: EL6 | Check if reboot is required
  set_fact:
    reboot_needed: true
  when: "'kernel.' or 'kernel-firmware' or 'glibc.' 'hal.' in item"
  with_items: "{{ yum_result.results }}"

- name: EL 7 | Reboot target host if needed
  include: reboot.yml
  when:
    - reboot
    - yum_result | changed
    - ('Reboot is required' in needs_restarting.stdout)
    - ansible_distribution_major_version | version_compare('7', '=')

- name: EL 6 | Reboot target host if needed
  include: reboot.yml
  when:
    - reboot
    - yum_result | changed
    - reboot_needed
    - ansible_distribution_major_version | version_compare('6', '=')
