---
# tasks file for ec2-setup | RHEL

- name: Install python selinux libraries
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ ec2_setup_python }}"

- name: Set timezone | RHEL 7
  timezone:
    name: "{{ ec2_setup_timezone }}"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "7"

- name: Set timezone | RHEL 6
  file:
    src: "/usr/share/zoneinfo/{{ ec2_setup_timezone }}"
    dest: /etc/localtime
    force: yes
    state: link
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version == "6"
